### ISSUE TITLE
Timed out while getting machine addresses error

### ISSUE THREAD

**Issue by mateuszlewko** [JanMa/nomad-driver-nspawn#14] opened 2020-09-05 20:09 UTC
Hi there,

thanks for this nomad plugin. I wanted to try out this driver but I get the above error when allocating job.
I can see in the driver's code when the error is raised, but I'm not able to understand why it fails to get the machine address. 
Could you advise me on why is that happening? 

I have nspawn installed and I was able to successfully boot and play around with nspawn container outside of nomad.
I'm running all this on a fresh Ubuntu 20.04 instance. Is there anything on my machine I could check that would provide more info? 

#### Nomad job
```
job "debian" {
  type = "service"
    
  datacenters = ["dc1"]

  group "debian" {
    task "debian" {
      driver = "nspawn"
      config {
        image = "debian-buster"
        resolv_conf = "copy-host"
        image_download {
          url = "https://nspawn.org/storage/debian/buster/tar/image.tar.xz"
        }
      }

      resources {
        cpu    = 2000
        memory = 1024
      }
    }
  }
}
```

#### Result of `nomad alloc status`
> Recent Events:
Time                       Type             Description
2020-09-05T21:59:05+02:00  Alloc Unhealthy  Unhealthy because of failed task
2020-09-05T21:59:05+02:00  Not Restarting   Error was unrecoverable
2020-09-05T21:59:05+02:00  Driver Failure   rpc error: code = Unknown desc = timed out while getting machine addresses: <nil>
2020-09-05T21:59:05+02:00  Driver           buster login:
2020-09-05T21:59:05+02:00  Driver           Failed to set alternative interface name 've-debian-b594aee4-72b5-aa4d-12b8-3178280d1d08' to 've-debian-buTh1', ignoring: Operation not supported
2020-09-05T21:58:32+02:00  Driver           Downloading image
2020-09-05T21:58:32+02:00  Task Setup       Building Task Directory

**Comment by JanMa** [comment] 2020-09-06 11:15
Hello,

tank you for your interest in my project :-) It looks like `systemd-nspawn` is unable to rename the network interface which automatically gets created when starting the container. Therefore you see the following error message:
```
2020-09-05T21:59:05+02:00 Driver Failed to set alternative interface name 've-debian-b594aee4-72b5-aa4d-12b8-3178280d1d08' to 've-debian-buTh1', ignoring: Operation not supported
```

I can recreate this issue when spinning up Ubuntu 20.04 inside a [Vagrant Box](https://app.vagrantup.com/generic/boxes/ubuntu2004) and running the following commands:

```shell
# apt install systemd-container
# machinectl pull-tar https://nspawn.org/storage/debian/buster/tar/image.tar.xz --verify no debian.buster
# systemd-nspawn -D /var/lib/machines/debian.buster/ -n -U
Spawning container debian.buster on /var/lib/machines/debian.buster.
Press ^] three times within 1s to kill container.
Selected user namespace base 1441464320 and range 65536.
Using default interface naming scheme 'v245'.
Network interface name 've-debian.buster' has been changed to 've-debian.bR0zA' to fit length constraints.
Failed to set alternative interface name 've-debian.buster' to 've-debian.bR0zA', ignoring: Operation not supported
```

Nevertheless the container starts up just fine and has an IP address assigned. Also when I install the latest Nomad version with this driver in the Vagrant Box, the Job you posted is starting just fine for me. 

If you take a look at the Nomad logs, you will see the actual command the driver uses to invoke `systemd-nspawn`. In my case it looked like this:
```
2020-09-06T10:47:14.088Z [INFO]  client.driver_mgr.nomad-driver-nspawn: commad arguments: driver=nspawn @module=nspawn args=[-D, /var/lib/machines/debian-buster, --boot, --network-veth, -U, --machine, debian-e
7e1e2f7-fdb0-7f5a-fd3f-7def498ce579, --resolv-conf, copy-host, --bind, /tmp/NomadClient028801089/e7e1e2f7-fdb0-7f5a-fd3f-7def498ce579/alloc:/alloc, --bind, /tmp/NomadClient028801089/e7e1e2f7-fdb0-7f5a-fd3f-7def498
ce579/debian/local:/local, --bind, /tmp/NomadClient028801089/e7e1e2f7-fdb0-7f5a-fd3f-7def498ce579/debian/secrets:/secrets, -E, NOMAD_ALLOC_DIR=/alloc, -E, NOMAD_JOB_NAME=debian, -E, NOMAD_DC=dc1, -E, NOMAD_TASK_NA
ME=debian, -E, NOMAD_ALLOC_ID=e7e1e2f7-fdb0-7f5a-fd3f-7def498ce579, -E, NOMAD_TASK_DIR=/local, -E, NOMAD_GROUP_NAME=debian, -E, NOMAD_ALLOC_INDEX=0, -E, NOMAD_SECRETS_DIR=/secrets, -E, NOMAD_REGION=global, -E, NOM
AD_ALLOC_NAME=debian.debian[0], -E, NOMAD_CPU_LIMIT=100, -E, NOMAD_MEMORY_LIMIT=300, -E, NOMAD_NAMESPACE=default, --property=MemoryMax=314572800] timestamp=2020-09-06T10:47:14.084Z
```

One thing you could try is to run this command manually (ignoring all the `--bind` and `-E` arguments). Maybe this can help you track down the issue why your container is not getting an IP address. 

Kind regards,
Jan

**Comment by JanMa** [comment] 2020-09-06 18:58
I think I found the root cause of your issue. If you are using the Ubuntu 20.04 Desktop version (which I think you are), the `systemd-networkd.service` is disabled by default. You will need to enable and start it, then `systemd-nspawn` containers that are started with private networking enabled will get an IP address assigned on startup.

I wrote a blog-post on the topic of getting `systemd-nspawn` up and running some time ago, maybe this will be helpful for you:
https://janma.tk/2019-10-13/systemd-nspawn/

Please let me know if enabling the service solved your problem, then we can close this issue :-)

**Comment by mateuszlewko** [comment] 2020-09-09 21:32
Thank you for quick reply! Yes it fixed this issue. I initially though that those services have to be enabled on the host. By enabling them in the container `systemd-nspawn` assigns IP address and the job starts fine. Also thanks for the article. 
As a side note, you may want to look at this fork: https://github.com/arianvp/nomad-driver-nspawn/commits/master. The author of that fork removed some port mapping & machine address code.

**Closed** 2020-09-09 21:32 UTC
